/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 04 12:44:04 GMT 2025
 */

package evosuite.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelPromise;
import org.apache.bookkeeper.util.ByteBufList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ByteBufList_ESTest extends ByteBufList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
      byte[] byteArray0 = new byte[3];
      int int0 = byteBufList1.getBytes(byteArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
      ByteBuf byteBuf1 = ByteBufList.coalesce(byteBufList1);
      assertNotSame(byteBuf1, byteBuf0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBuf byteBuf1 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf1, byteBuf0);
      assertFalse(byteBufList1.equals((Object)byteBufList0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBufList byteBufList1 = (ByteBufList)byteBufList0.touch((Object) byteBufList0);
      assertEquals(0, byteBufList1.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      int int0 = byteBufList0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      ByteBuf byteBuf0 = byteBufList0.getBuffer(0);
      assertNull(byteBuf0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
      ByteBuf byteBuf1 = byteBufList1.getBuffer((byte)1);
      assertSame(byteBuf1, byteBuf0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBufList byteBufList1 = ByteBufList.clone(byteBufList0);
      assertNotSame(byteBufList1, byteBufList0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
      byte[] byteArray0 = byteBufList1.array();
      assertEquals(0, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.touch((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.toArray();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      byteBufList0.release();
      // Undeclared exception!
      try { 
        byteBufList0.retain();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // refCnt: 0, increment: 1
         //
         verifyException("io.netty.util.internal.ReferenceCountUpdater", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null, (ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.readableBytes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.hasArray();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }



  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.getBytes((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      // Undeclared exception!
      try { 
        byteBufList0.getBuffer((-5042));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }





  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
      byteBufList1.release();
      byteBufList1.add(byteBuf0);
      // Undeclared exception!
      try { 
        ByteBufList.coalesce(byteBufList1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // refCnt: 0
         //
         verifyException("io.netty.buffer.AbstractByteBuf", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try { 
        ByteBufList.coalesce((ByteBufList) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)0).when(byteBuf0).capacity();
      doReturn((int)(byte)1, (int)(byte)0).when(byteBuf0).readableBytes();
      doReturn((int)(byte)1).when(byteBuf0).readerIndex();
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      // Undeclared exception!
      try { 
        ByteBufList.coalesce(byteBufList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // srcIndex: 1, length: 0 (expected: range(0, 0))
         //
         verifyException("io.netty.buffer.AbstractByteBuf", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn((-2344)).when(byteBuf0).readableBytes();
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      // Undeclared exception!
      try { 
        ByteBufList.coalesce(byteBufList0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -2344 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        ByteBufList.clone((ByteBufList) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.arrayOffset();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
      // Undeclared exception!
      try { 
        byteBufList0.array();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      // Undeclared exception!
      try { 
        byteBufList0.array();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
      ByteBufList byteBufList2 = byteBufList1.retain();
      ByteBufList byteBufList3 = ByteBufList.clone(byteBufList2);
      byte[] byteArray0 = new byte[0];
      int int0 = byteBufList3.getBytes(byteArray0);
      assertEquals(0, int0);
      assertNotSame(byteBufList3, byteBufList2);
      assertEquals(1, byteBufList3.size());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
      int int0 = byteBufList1.readableBytes();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      byteBufList0.add(byteBuf0);
      int int0 = byteBufList0.arrayOffset();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
      ChannelPromise channelPromise0 = mock(ChannelPromise.class, new ViolatedAssumptionAnswer());
      doReturn((ChannelPromise) null).when(channelPromise0).addListener(any(io.netty.util.concurrent.GenericFutureListener.class));
      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
      doReturn(channelPromise0).when(channelHandlerContext0).newPromise();
      doReturn((ChannelPromise) null).when(channelHandlerContext0).voidPromise();
      doReturn((ChannelFuture) null, (ChannelFuture) null).when(channelHandlerContext0).write(any() , any(io.netty.channel.ChannelPromise.class));
      ChannelPromise channelPromise1 = mock(ChannelPromise.class, new ViolatedAssumptionAnswer());
      byteBufList1.ENCODER.write(channelHandlerContext0, byteBufList1, channelPromise1);
      assertEquals(2, byteBufList1.size());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      try { 
        byteBufList0.ENCODER.write((ChannelHandlerContext) null, (Object) null, (ChannelPromise) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.util.ByteBufList$Encoder", e);
      }
  }


  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
      boolean boolean0 = byteBufList1.hasArray();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(byteBuf0).hasArray();
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      boolean boolean0 = byteBufList0.hasArray();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      boolean boolean0 = byteBufList0.hasArray();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ByteBufList.Encoder byteBufList_Encoder0 = new ByteBufList.Encoder();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      // Undeclared exception!
      try { 
        byteBufList0.getBuffer(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      ByteBufList byteBufList1 = byteBufList0.retain();
      assertSame(byteBufList0, byteBufList1);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      int int0 = byteBufList0.size();
      assertEquals(1, int0);
  }



  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ByteBufList byteBufList0 = ByteBufList.get();
      // Undeclared exception!
      try { 
        byteBufList0.arrayOffset();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn((byte[]) null).when(byteBuf0).array();
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      byte[] byteArray0 = byteBufList0.array();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ByteBuf byteBuf0 = mock(ByteBuf.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(byteBuf0).readableBytes();
      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
      byte[] byteArray0 = byteBufList0.toArray();
      assertEquals(0, byteArray0.length);
  }
}
