/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 04 11:52:28 GMT 2025
 */

package evosuite.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.BufferOverflowException;
import java.nio.BufferUnderflowException;
import java.nio.ByteBuffer;
import org.apache.bookkeeper.bookie.LogMark;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class LogMark_ESTest extends LogMark_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      

      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      LogMark logMark1 = LogMark.MAX_VALUE;
      assertNotSame(logMark1, logMark0);
      assertNotNull(logMark1);
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertFalse(logMark1.equals((Object)logMark0));
      
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(1364);
      assertNotNull(byteBuffer0);
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals(0, byteBuffer0.position());
      assertEquals(1364, byteBuffer0.limit());
      assertEquals(1364, byteBuffer0.capacity());
      assertTrue(byteBuffer0.hasRemaining());
      assertTrue(byteBuffer0.isDirect());
      assertFalse(byteBuffer0.hasArray());
      assertEquals("java.nio.DirectByteBuffer[pos=0 lim=1364 cap=1364]", byteBuffer0.toString());
      assertEquals(1364, byteBuffer0.remaining());
      
      String string0 = logMark1.toString();
      assertNotSame(logMark1, logMark0);
      assertNotNull(string0);
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertFalse(logMark1.equals((Object)logMark0));
      assertEquals("LogMark: logFileId - 9223372036854775807 , logFileOffset - 9223372036854775807", string0);
  }



  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      LogMark logMark1 = new LogMark(logMark0);
      assertNotNull(logMark1);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, logMark1.getLogFileOffset());
      assertEquals(0L, logMark1.getLogFileId());
      assertFalse(logMark1.equals((Object)logMark0));
  }



  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(1364);
      assertNotNull(byteBuffer0);
      assertEquals("java.nio.DirectByteBuffer[pos=0 lim=1364 cap=1364]", byteBuffer0.toString());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(1364, byteBuffer0.capacity());
      assertEquals(1364, byteBuffer0.remaining());
      assertFalse(byteBuffer0.hasArray());
      assertTrue(byteBuffer0.isDirect());
      assertEquals(1364, byteBuffer0.limit());
      assertEquals(0, byteBuffer0.position());
      assertFalse(byteBuffer0.isReadOnly());
      
      logMark0.MAX_VALUE.readLogMark(byteBuffer0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(1364, byteBuffer0.capacity());
      assertEquals("java.nio.DirectByteBuffer[pos=16 lim=1364 cap=1364]", byteBuffer0.toString());
      assertEquals(1348, byteBuffer0.remaining());
      assertFalse(byteBuffer0.hasArray());
      assertTrue(byteBuffer0.isDirect());
      assertEquals(1364, byteBuffer0.limit());
      assertEquals(16, byteBuffer0.position());
      assertFalse(byteBuffer0.isReadOnly());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      long long0 = logMark0.getLogFileOffset();
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      logMark0.setLogMark((-2633L), (-3166L));
      assertEquals((-2633L), logMark0.getLogFileId());
      assertEquals((-3166L), logMark0.getLogFileOffset());
      
      long long0 = logMark0.getLogFileOffset();
      assertEquals((-2633L), logMark0.getLogFileId());
      assertEquals((-3166L), logMark0.getLogFileOffset());
      assertEquals((-3166L), long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      
      long long0 = logMark0.getLogFileId();
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, long0);
      
      long long1 = logMark0.getLogFileOffset();
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertTrue(long1 == long0);
      assertEquals(9223372036854775807L, long1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LogMark logMark0 = new LogMark((-767L), (-767L));
      assertNotNull(logMark0);
      assertEquals((-767L), logMark0.getLogFileId());
      assertEquals((-767L), logMark0.getLogFileOffset());
      
      long long0 = logMark0.getLogFileId();
      assertEquals((-767L), logMark0.getLogFileId());
      assertEquals((-767L), logMark0.getLogFileOffset());
      assertEquals((-767L), long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(1);
      assertNotNull(byteBuffer0);
      assertTrue(byteBuffer0.hasRemaining());
      assertEquals(1, byteBuffer0.remaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isDirect());
      assertEquals(1, byteBuffer0.limit());
      assertEquals(1, byteBuffer0.capacity());
      assertFalse(byteBuffer0.isReadOnly());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(0, byteBuffer0.position());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=1 cap=1]", byteBuffer0.toString());
      
      // Undeclared exception!
      try { 
        logMark0.writeLogMark(byteBuffer0);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      
      // Undeclared exception!
      try { 
        logMark0.readLogMark((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.LogMark", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      
      // Undeclared exception!
      try { 
        logMark0.compare((LogMark) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.LogMark", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LogMark logMark0 = null;
      try {
        logMark0 = new LogMark((LogMark) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.LogMark", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, logMark0.getLogFileOffset());
      
      LogMark logMark1 = LogMark.MAX_VALUE;
      assertNotSame(logMark1, logMark0);
      assertNotNull(logMark1);
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertFalse(logMark1.equals((Object)logMark0));
      
      int int0 = logMark0.compare(logMark1);
      assertNotSame(logMark0, logMark1);
      assertNotSame(logMark1, logMark0);
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertFalse(logMark0.equals((Object)logMark1));
      assertFalse(logMark1.equals((Object)logMark0));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      
      int int0 = logMark0.compare(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, logMark0.getLogFileOffset());
      
      LogMark logMark1 = LogMark.MAX_VALUE;
      assertNotSame(logMark1, logMark0);
      assertNotNull(logMark1);
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertFalse(logMark1.equals((Object)logMark0));
      
      int int0 = logMark1.compare(logMark0);
      assertNotSame(logMark0, logMark1);
      assertNotSame(logMark1, logMark0);
      assertEquals(0L, logMark0.getLogFileId());
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark1.getLogFileOffset());
      assertEquals(9223372036854775807L, logMark1.getLogFileId());
      assertFalse(logMark0.equals((Object)logMark1));
      assertFalse(logMark1.equals((Object)logMark0));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LogMark logMark0 = LogMark.MAX_VALUE;
      assertNotNull(logMark0);
      assertEquals(9223372036854775807L, logMark0.getLogFileId());
      assertEquals(9223372036854775807L, logMark0.getLogFileOffset());
      
      // Undeclared exception!
      try { 
        logMark0.writeLogMark((ByteBuffer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.LogMark", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LogMark logMark0 = new LogMark();
      assertNotNull(logMark0);
      assertEquals(0L, logMark0.getLogFileOffset());
      assertEquals(0L, logMark0.getLogFileId());
      
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(0);
      assertNotNull(byteBuffer0);
      assertEquals(0, byteBuffer0.remaining());
      assertEquals(0, byteBuffer0.arrayOffset());
      assertFalse(byteBuffer0.isDirect());
      assertEquals(0, byteBuffer0.position());
      assertFalse(byteBuffer0.isReadOnly());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]", byteBuffer0.toString());
      assertTrue(byteBuffer0.hasArray());
      assertEquals(0, byteBuffer0.capacity());
      assertFalse(byteBuffer0.hasRemaining());
      assertEquals(0, byteBuffer0.limit());
      
      // Undeclared exception!
      try { 
        logMark0.readLogMark(byteBuffer0);
        fail("Expecting exception: BufferUnderflowException");
      
      } catch(BufferUnderflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }
}
